# Generated by Django 4.0.3 on 2022-03-30 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_pokemoncard_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemoncard',
            options={'ordering': ['rarity']},
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('site', models.URLField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pokemoncard')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
